fork = true
frame = "buttonless"
idle = true
maximized = false
no-multigrid = false
srgb = true
tabs = true
mouse-cursor-icon = "arrow"
title-hidden = true
vsync = true
wsl = false
# system-native-tabs feature is conflict with neovide_macos_simple_fullscreen feature
# see: https://github.com/neovide/neovide/issues/2378#issuecomment-3591523690
system-native-tabs = false

[font]
size = 12
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "JetBrainsMono Nerd Font Propo"
style = "Regular"

[[font.bold]]
family = "JetBrainsMono Nerd Font Propo"
style = "ExtraBold"

[[font.italic]]
family = "JetBrainsMono Nerd Font Propo"
style = "Bold Italic"

[[font.bold_italic]]
family = "JetBrainsMono Nerd Font Propo"
style = "ExtraBold Italic"

[box-drawing]
mode = "font-glyph"

[box-drawing.sizes]
default = [2, 4]
