fork = true
frame = "buttonless"
idle = true
maximized = false
no-multigrid = false
srgb = true
tabs = true
theme = "auto"
mouse-cursor-icon = "arrow"
title-hidden = true
vsync = true
wsl = false

[font]
size = 12
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "JetBrainsMono Nerd Font Propo"
style = "Regular"

[[font.bold]]
family = "JetBrainsMono Nerd Font Propo"
style = "ExtraBold"

[[font.italic]]
family = "JetBrainsMono Nerd Font Propo"
style = "Bold Italic"

[[font.bold_italic]]
family = "JetBrainsMono Nerd Font Propo"
style = "ExtraBold Italic"

[box-drawing]
mode = "font-glyph"

[box-drawing.sizes]
default = [2, 4]
